import consola from "consola";
import fs from "fs";
import path from "path";

import { GenerateItemsEnum } from "./lib/GenerateItemsEnum.js";

// Check if items.json exists
const itemsJsonPath = path.join(process.cwd(), "items.json");
if (!fs.existsSync(itemsJsonPath)) {
  consola.error("items.json not found in the current directory.");
  process.exit(1);
}

async function main() {
  try {
    const generator = new GenerateItemsEnum();
    generator.loadFromFile(itemsJsonPath);

    const itemsVersion = generator.itemsVersion;
    const itemsCount = generator.itemsCount;
    consola.info(`Loaded items.json - Version: ${itemsVersion}, Items Count: ${itemsCount}`);

    const enumString = generator.buildEnum(4);

    // Add some credit and pragma once
    const creditComment = 
    `/* Generated by Growtopia Items Enum Generator` +
    `\nVersion: ${itemsVersion}, Items Count: ${itemsCount}` +
    `\nGenerated on: ${new Date().toISOString()}` +
    `\n\n @see https://github.com/GTPSHAX/growtopia-items-enum-generator - our repository` +
    `*/\n`;
    const result = `#ifndef ITEMS_ENUM_H\n#define ITEMS_ENUM_H\n\n${creditComment}${enumString}\n#endif // ITEMS_ENUM_H\n`;

    fs.writeFileSync(path.join(process.cwd(), "ItemsEnum.h"), result, "utf-8");
    consola.success("Enum generated successfully:\n");
  } catch (error) {
    consola.error("An error occurred:", error);
    process.exit(1);
  }
}

main();